### ISSUE TITLE
Link to PDF in README.adoc gives 404.

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-georeferencing-quick-guide#1]

**Comment by ArthurChapman** [comment]
Working for me today, @tucotuco

**Comment by tucotuco** [comment]
The link to the temporary HTML and PDF Qucik Reference Guide on https://github.com/gbif/doc-georeferencing-quick-reference-guide/blob/1.0/README.adoc
akes me to https://docs.gbif-uat.org/georeferencing-quick-reference-guide/en/, which is not found.

**Comment by ArthurChapman** [comment]
Ah OK - that link doesn't work, but the link at the top of https://docs.gbif-uat.org/georeferencing-quick-reference-guide/1.0/en/ works OK
