### ISSUE TITLE
2.1.3.9 Additional consideration to reduce uncertainty

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-quick-guide#10]
In 2.1.3.9. Feature – between Two Features, an additional consideration can be made in order to reduce the uncertainty if there is a constraint by elevation. Taking the coordinate at the point where the elevation contour or elevation pixel intersects or is near to the line that joins the features. The uncertainty will be the distance between the coordinate taken and the middle point of the line that joins the features. Showing an example below. 

![image](https://user-images.githubusercontent.com/15789737/97746678-c10b9b00-1ab8-11eb-9220-b20acd9589f9.png)

¿Could this method be incorporated in the document?

**Comment by tucotuco** [comment]
This example is actually already covered in https://docs.gbif-uat.org/georeferencing-quick-reference-guide/1.0/en/#feature-path.
