### ISSUE TITLE
Rewrite section 2.2.3.1. Offset along a Narrow Path

### ISSUE THREAD

**Issue by ArthurChapman** [gbif/doc-georeferencing-quick-guide#11]
From @tuco moved from https://github.com/gbif/doc-georeferencing-best-practices/issues/41.

It occurred to me while resolving one such locality, that the use of the corrected center on the relevant part of the path is not the best reference point, nor is using the radius of the reference entity to add to the final coordinates. It would be fine if all the route was straight, but that is never the case, which means the method described is always going to be bigger than it needs to be. That in itself is conservative, so not "wrong", but it could be better.

**Comment by tucotuco** [comment]
The proposed new content is as follows.

**Locality Type**: Distance along path

**Step 1 – Determine the feature boundaries**: Find the boundary of the intersection of the reference feature with the path as you would for Feature – Junction, Intersection, Crossing, Confluence (Figure 18).

**Step 2 – Determine the starting feature coordinates and length of the matching path**: Once the boundary of the starting feature has been determined, find the midpoint along the path within the boundary of the feature it intersects with (Figure 18B). Note the distance along the path from the midpoint to the boundary of the feature it intersects in the direction of the offset. Enter the length of that segment in "Radial of Feature" in the Georeferencing Calculator.

**Step 3 – Enter the "Input Latitude" and "Longitude"**: Enter the coordinates of the offset position, which can be determined by measuring the length along the midline of the path from the midpoint found in the previous step to the distance along the path given in the locality description. See the notes on map scale and accumulated error in "Offset – Distance along a Path".

**Step 4 – Calculate using the following additional parameters in the Calculator**: Coordinate Source, Coordinate Format, Datum, Coordinate Precision, Measurement Error, Distance Units, Distance Precision (see "Georeferencing Concepts").

_Figure 18. A locality of the type "Offset along a path" where the path is narrow, specifically, along a road "east of" a feature. A: Inset showing the boundary, midpoint ⓐ, and half the distance along the path inside the feature ⓑ. B: The midpoint ⓐ and the offset ⓓ measured along the road._

**Comment by tucotuco** [comment]
Addressed in 0263797715209f75d341790bf2621f8edef60ec0.

**Comment by tucotuco** [comment]
Still needs updated Figure to reflect the recent changes.

**Comment by pzermoglio** [comment]
Content checked. Closing this issue.
