### ISSUE TITLE
Rewrite section 2.2.3.2. Offset along a Wide Path

### ISSUE THREAD

**Issue by ArthurChapman** [gbif/doc-georeferencing-quick-guide#12]
From @tucotuco Moved from https://github.com/gbif/doc-georeferencing-best-practices/issues/40 as refers to Quick Reference Guide

New Figure and updated methodology ready to replace what is in that section currently.

**Comment by tucotuco** [comment]
The proposed new content is as follows:

### Offset along a Wide Path

**Example**
"Mississippi River, 16 mi downstream from St. Louis"

**Locality Type:** Distance along path

**Step 1 – Determine the starting feature boundaries**: Find the center of the intersection of the reference feature with the path as you would for Feature – Junction, Intersection, Crossing, Confluence (Figure 19A).

**Step 2 – Determine the starting feature coordinates and geographic radial**: Once the boundary of the starting feature has been determined, use the same method to determine the corrected center and geographic radial as for Feature – with Obvious Spatial Extent, namely, measure the distance from the coordinates of the corrected center to the furthest point on the boundary of the starting feature (Figure 19A).

**Step 3 – Calculate preliminary uncertainties**: Calculate a preliminary uncertainty by entering the geographic radial from **Step 1** into the Radial of feature in the Georeferencing Calculator and fill in the rest of the parameters for the Distance along path locality type.

**Additional parameters for Step 3**: Coordinate Source, Coordinate Format, Datum, Coordinate Precision, Measurement Error, Distance Units, Distance Precision (see Georeferencing Concepts).

**Step 4 – Final path boundary**: The objective of this step is to estimate a boundary around the set of possible paths matching the description. To do so, we need to trace at least three of the possible paths. The first of these paths is from the coordinates of **Step 2** along one side of the wide path to a distance equal to the offset distance given in the locality description. The second path is similar, but along the opposite side of the wide path starting at a point of equal elevation and tracing along that opposite side. The third path is from the coordinates of **Step 2** to the offset distance to then along the middle of the wide path (or the deepest channel if locatable in the case of a waterway). If there are other reasonably likely paths that are very different from these three, trace them in a similar manner. Each of these paths terminate at an X in the example in Figure 19B. From each of these termination points, trace both forward and backward to a distance equal to the uncertainty determined in **Step 3** (the segments of the paths marked with u in Figure 19B). The outer endpoints of all the segments marked with u form a polygon (Figure 19B). This polygon is the final path boundary we seek.

**Step 5 – Final path boundary corrected center and geographic radial**: Once you have determined the boundary of the final path boundary from **Step 4**, treat as for Feature – with Obvious Spatial Extent, namely, find the corrected center of the final path boundary and measure the distance from there to the furthest point on the boundary. Use the coordinates of the corrected center for the resulting Latitude and Longitude and use the length of the geographic radial of the final path boundary as the final Uncertainty. Use all of the rest of the output values from the calculation in **Step 4** in the final georeference. No new calculation has to be made for this step.

[Figure 19]
Determination of the final coordinates and geographic radial for a locality of the type Offset along path, where the path is wide enough that there are multiple reasonable routes within it, in this case a river. **A**: Boundary, corrected center (a₁) and geographic radial (b₁) for the starting feature. **B**: Offsets (x) along varies routes along the wider path, buffers of uncertainty (u) forward and backward along the possible paths, and the boundary (red dotted segments) defined by the buffers. **C**: Boundary, corrected center (a₂) and geographic radial (b₂) for the section of the river covered by the distance X downstream from the corrected center of the starting feature (a₁) buffered by the uncertainties (u).

**Comment by tucotuco** [comment]
Textual solution provided in 58cabc12a3b7fb9783cd851c1e4acbf4e83fd2e3

**Comment by tucotuco** [comment]
Figure updated as well, needs to be checked in production before release.

**Comment by ArthurChapman** [comment]
Probably my lack of being able to trace some of this, but if on 58cabc1 I look under "Display the Rich difference - I see:

![image](https://user-images.githubusercontent.com/22837459/101828273-6cfad880-3b85-11eb-91ae-7d7c3de99cc5.png)

I am not sure where some of this has come from.  My concern is that in line 4 of that, "varies" should be "various"

**Comment by tucotuco** [comment]
Varies changed to various in 9ebf6ce42b1795a61ed2612d1a2ae56744de4260.

**Comment by pzermoglio** [comment]
Content checked. Closing this issue.
