### ISSUE TITLE
3.4.2 Google Earth Measurements

### ISSUE THREAD

**Issue by ArthurChapman** [gbif/doc-georeferencing-quick-guide#13]
In __§3.4.2__ under __§Using OpenStreetMap, Google Maps and Google Earth__

At the end of the paragraph

"The positional error on Google Maps and Google Earth is poorly documented and varies both geographically and with imagery resolution. We recommend the conservative combination of root mean square error from Google Earth and Landsat imagery of 89.7m estimate derived by Potere 2008 for Google Earth or Google Map readings in or before 2008. After that, we recommend the 8m (95 per cent confidence interval) estimated by Paredes-Hernández et al. 2013. Limited data based on the accuracy of street junctions on OpenStreetMap (Helbich et al. 2012) suggests that this source has accuracy of the same order of magnitude as the Google products."

Add a sentence:

"Note that measurements in Google Earth and Google Maps are direct lines and don't account for changes in elevation."

**Comment by tucotuco** [comment]
Recommend changing the added sentence from:

"Note that measurements in Google Earth and Google Maps are direct lines and don't account for changes in elevation."

to

"Note that surface distance measurements in Google Earth and Google Maps do not account for changes in elevation."

**Comment by ArthurChapman** [comment]
This issue should have been under The Georeferencing Best Practices. The sentence has been incorporated and this issue is now closed
