### ISSUE TITLE
Add section for determining corrected center and radial

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-georeferencing-quick-guide#14]
In the Chilean Georeferencing Course in the GBIF CESP project "[Tackling the spatial challenge in the Southern Cone through georeferencing training](https://www.gbif.org/es/project/65NXZ9iEW2vkaZm6ZjF6w4/tackling-the-spatial-challenge-in-the-southern-cone-through-georeferencing-training)", we developed a slide series to explain how to simplify the sometimes mystifying process of determining the corrected center and least bounding circles. It would be extremely useful to add this as a new section to the QRG. I propose that the new section be an Appendix B.
References to this new section should be added to section [1.6.2](https://docs.gbif-uat.org/georeferencing-quick-reference-guide/1.0/en/#s-corrected-center) and [1.6.3](https://docs.gbif-uat.org/georeferencing-quick-reference-guide/1.0/en/#radial-of-feature).
This new material doesn't fit well in either of the two sections mentioned above. If it is injected in the methods, I think it would have to go after all the others as "2.5 Determining the Corrected Center and Geographic Radial".  Then, every place it is mentioned to determine the corrected center and geographic radial should have a reference to this new section.

**Comment by tucotuco** [comment]
First draft added in f5b76b1cdae383bc753f285594d2e1d208c7e086. No references to this have been made from other sections yet. I don't know how to do the layout for the images that go with the text. Ideally, the images would be either to the left or right of the text that goes with them. And example of how I envision it can be found in slides 27-32 in the [Tipos de Localidad Presentation](https://docs.google.com/presentation/d/19VPMJ8ddhBgZOym_HrKI5CIbTvMq_IRB79KPaOeBOKM/edit#slide=id.ga0d0377b0a_0_0). Need help how to do the layout.
Five of the images for this section will get replacements sometime after 14 Dec to clean up some inconsistencies.

**Comment by ArthurChapman** [comment]
I can't see any text - only the one deleted/added image

**Comment by tucotuco** [comment]
You're right. I put in the wrong commit reference. It should be this one, 14c23f8f37c81766903f291c5197de8066ef82a5.

**Comment by tucotuco** [comment]
References added in 23481731156f1a163b0e973e82b124961933e304. Appendix addition ready.

**Comment by tucotuco** [comment]
Completed with ddc99aed387e0bc80c24d3907963d721e2fbf4f4.

**Comment by kcopas** [comment]
I see this one's assigned to me and has had a lot of moving parts since that point. Looks like you've figured out the addition to the index and side-by-side display of image-and-text (well done!). What remains: new images (post-14 Dec)? Cross-references in §1.6.2 and .3? Anything else?

At a glance, my one suggestion is that the intro should just link to the glossary definition of corrected center (which is both a bit longer and worded slightly differently) and adding one for geographic radial. Is there a reason you want the former pulled out and restated here?

**Comment by tucotuco** [comment]
Images updated in bda110fcd735d90743c6387eb41fca53a27d068e. Cross-references added. Redundant definitions removed in d6013439c7f1f35bda70684aa56a229901f19a58.  All done for this issue.
