### ISSUE TITLE
Rewrite Section 2.2.3.3

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-georeferencing-quick-guide#15]
...to be consistent with the changes to previous two sections and with the Figure.

**Comment by tucotuco** [comment]
Proposed solution is to change Step 3 and the image caption to the following:

**Step 3 – Determine the final coordinates and geographic radial**: Treat the set of boundaries from **Step 2** and the minimum area between them as parts of the same feature. Find the corrected center and geographic radial for this combined feature (Figure 20B). Use the coordinates of the corrected center of this combined feature for the resulting Input _Latitude_ and _Longitude_ and use the length of the geographic radial of the combined feature as the final uncertainty. No further calculation is necessary.

Figure 20.
Determination of the input coordinates and geographic radial for a Locality Type _Offset along path_ where there are multiple possible paths matching the locality description, in this case two roads out of a town. **A**: Inset showing the boundaries, midpoints (a₁ and a₂), and distances from midpoints to outer edges (shown as geographic radials b₂ and b₂) of the intersections of the paths and the starting feature. **B**: Boundary, corrected center (a₃) and geographic radial (b₃) for the combination of the two road sections, each defined by offsets at a distance X along the respective paths from their respective midpoints in the starting feature, plus or minus the uncertainties determined for the _Distance along a Path_ locality type (u).

**Comment by ArthurChapman** [comment]
Looks OK

**Comment by tucotuco** [comment]
Solution provided in 79f83609143d67f4ee1a34141e731744f561a4ac.

**Comment by pzermoglio** [comment]
Content checked. Closing this issue.
