### ISSUE TITLE
Check how we mention Google Maps and Google Earth 

### ISSUE THREAD

**Issue by pzermoglio** [gbif/doc-georeferencing-quick-guide#26]
Google Maps and Google Earth should be named Google Maps<sup>TM</sup> and Google Earth<sup>TM</sup> throughout the document.

**Comment by tucotuco** [comment]
These were in the original and removed, including in quoted examples. Any particular reason why @MattBlissett or @kcopas ?

**Comment by kcopas** [comment]
We have no stake in protecting private trademarks, so including them only serves to distract a reader.

=====
Kyle Copas
GBIF Secretariat
+45 28 75 14 75

Sent from my iPhone: thumbs don’t fejl mig nu
________________________________

**Comment by tucotuco** [comment]
OK.
