### ISSUE TITLE
Check consistency of hyphenated words

### ISSUE THREAD

**Issue by pzermoglio** [gbif/doc-georeferencing-quick-guide#27]
In particular, there are a couple of "corrected-center" and "geographic-radial" that should be "corrected center" and "geographic radial", respectively. Needs to be checked in all sections just in case.

**Comment by ArthurChapman** [comment]
Corrected in 40f35ca

**Comment by tucotuco** [comment]
Found and fixed all the remaining hyphen and dash issues.
