### ISSUE TITLE
Check mentions to Section 2 title (changed)

### ISSUE THREAD

**Issue by pzermoglio** [gbif/doc-georeferencing-quick-guide#28]
Title for section 2 has changed from "Georeferencing Methods for Locality Type" to "Georeferencing Methods by Locality Type". Check other sections for potential mentions to it by its title.

**Comment by ArthurChapman** [comment]
Corrected in 40f35ca

**Comment by pzermoglio** [comment]
Thanks @ArthurChapman. All checked, closing issue.
