### ISSUE TITLE
1.5 clarify example for dwc:georeferenceSources

### ISSUE THREAD

**Issue by ekrimmel** [gbif/doc-georeferencing-quick-guide#3]
"USGS 1:24000 Florence Montana Quad" is listed as an example for _dwc:georeferenceSources_ in the section, [Using Darwin Core](https://docs.gbif-uat.org/georeferencing-quick-reference-guide/1.0/en/#using-darwin-core), but the name and scale of the map here aren't really enough to be a good example of a source "described specifically enough to allow anyone in the future to use the same resources." To accomplish that we need a year, i.e. "USGS 1:24000 Florence Montana Quad 1967." I know this example comes straight from the DwC examples, so perhaps better to fix it there first but either way this Quick Reference Guide deserves to be providing nice, clear examples.

**Comment by tucotuco** [comment]
Excellent recommendation! Thanks @ekrimmel.

**Comment by tucotuco** [comment]
Updated in Darwin Core and in commit d63678abc796b7d839d8c530902334a4eb872c29.
