### ISSUE TITLE
Change in coordinateUncertaintyInMeters term example based on the recommendation of best practices and quick guide

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-quick-guide#7]
In chapter "1.6.15. GPS Accuracy", I think this is a very important recommendation for documentation that goes beyond the workflow of georeferencing and is necessary to document explicitly in the examples of the DwC term [_coordinateUncertaintyInMeters_](https://dwc.tdwg.org/list/#dwc_coordinateUncertaintyInMeters). Actually, the recommendation for unknown uncertainty doesn't match completely with the actual example of the term:  "(reasonable lower limit of a GPS reading under good conditions if the actual precision was not recorded at the time). 71 (uncertainty for a UTM coordinate having 100-meter precision and a known spatial reference system)."

**Comment by tucotuco** [comment]
Term change requested in Darwin Core. Closing.
