### ISSUE TITLE
Coordinates with locality description

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-quick-guide#9]
In the Colombian georeferencing protocol there is a particular consideration for cases with a textual description of locality and coordinates, but the coordinates do not exactly match the description, in this case, there is an uncertainty calculation based on the distance of the coordinate and the location from the description, I think this case is not included in the guide, but is it because you consider that this type of validation is not necessary or correct? or is not included because it is not so common?.

**Comment by tucotuco** [comment]
We consider that an inconsistency. Something is wrong, and unless there is further evidence to resolve the inconsistency, we recommend either to not georeference it, and say why, or to georeference at the next higher level of geography that contains both options.
